version: '3.8'

services:
  payload:
    container_name: payload-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: pnpm start
    env_file:
      - .env
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
